version: 3.0.{build}-preview
pull_requests:  
  do_not_increment_build_number: true
branches:
  only:
  - master
build_script:
- ps: .\build.ps1
test: off
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet   
  api_key:
    secure: h64tYKeo97gSp/LH8V//qtd5nw/XFygDycymCl9eYRuUIHLCnHqiFaaKes+15wIL
  skip_symbols: true
  on:
    branch: master
notifications:
- provider: Email
  to:
  - zep519@yahoo.com
  subject: Build Notification
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
image: Visual Studio 2017

#install:
#  - cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
#  - cmd: dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log 

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
#https://andrewlock.net/publishing-your-first-nuget-package-with-appveyor-and-myget/
skip_commits:
  # Regex for matching commit message
  message: /docs.*/