# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# File matching patterns reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=vsts
pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/AB.Extensions.csproj'
    arguments: '--configuration $(buildConfiguration)'
    displayName: 'dotnet build'

# Execute Tests using CLI Task Runner
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx'
    displayName: 'Run Unit Tests'

#- script: dotnet publish 
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: '**/AB.Extensions.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    name: 'dotnet publish'

# Build agent not finding the trx files...
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    displayName: 'Publish Test Results'

# Pre-requisite task above for dotnet publish CLI
- task: PublishBuildArtifacts@1
